language: php

php:
    - 5.6
    - 7.2
    - 7.3

git:
  depth: 1

install:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev

script:
    - composer test
    - composer lint
