language: php

php:
    - 5.6
    - 7.2
    - 7.3

before_script:
    - echo 'error_log=/dev/null' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev

script:
    - vendor/bin/phpunit
    - vendor/bin/phpcs --standard=psr2 ./src/Yoti
