version: '3'

services:
  web:
      build: .
      ports:
          - "4002:443"
      volumes:
        - ./:/usr/share/nginx/html
      links:
          - php
  php:
      image: php:7-fpm-alpine
      volumes:
        - ./:/usr/share/nginx/html

  composer:
    image: composer
    volumes:
      - ../:/usr/share/yoti-php-sdk
    working_dir: /usr/share/yoti-php-sdk/examples
    command: update
